### ISSUE TITLE
Nombreux problèmes

### ISSUE THREAD

**Issue by KyneSilverhide** [MacNaab/trpg-pannel#1]
Je ne sais pas si le projet existe encore ou si tu le maintiens, mais en tout cas, il n'y a plus grand chose qui fonctionne :(

1. Ajout d'un marker sur la map (mode édition)
Application error: a client-side exception has occurred (developer guidance).
`framework-d0785ac6afe5ff41719e.js:1 TypeError: Cannot read properties of undefined (reading 'position')
    at Q (/_next/static/chunks/644.d04a5c174cb1b9b923f3.js:1)
    at ro (framework-d0785ac6afe5ff41719e.js:1)
    at Hu (framework-d0785ac6afe5ff41719e.js:1)
    at Pi (framework-d0785ac6afe5ff41719e.js:1)
    at _i (framework-d0785ac6afe5ff41719e.js:1)
    at xi (framework-d0785ac6afe5ff41719e.js:1)
    at vi (framework-d0785ac6afe5ff41719e.js:1)
    at framework-d0785ac6afe5ff41719e.js:1
    at t.unstable_runWithPriority (framework-d0785ac6afe5ff41719e.js:1)
    at $l (framework-d0785ac6afe5ff41719e.js:1)`
(sous Firefox et Chrome)

2.  Frise : erreur au chargement... "Erreur: Une erreur est survenu durant le chargement de la base de donnée. Consulter la console pour plus d'informations."
`Erreur lors du chargement des données: SyntaxError: JSON.parse: unexpected end of data at line 2 column 1 of the JSON data`
J'ai l'impression qu'il ne gère pas bien un fichier vide.. mais je n'ai pas trouvé comment (quel contenu)  le remplir moi même pour tester
(sous Firefox et Chrome)
Enregistrer ne semble pas non plus marcher... 

3. Edition des utilisateurs
Enregistrer n'enregistre rien... je reçois bien "["done"]" en console, mais si je recharge la page ca n'a pas enregistré. (mais je peux modifier moi meme le JSON, c'est moins grave)

Reproduction : tu peux essayer sur https://witcher.kyne.ovh/admin/ 
Ca utilise PHP8
PS : les fichiers JSON sont modifiables (pas de problèmes de droits) car ca marche si j'utilise "Exploration des DBs", je peux modifier et ca sauvegarde bien.

**Comment by MacNaab** [comment]
Le projet est en pause (car ma campagne l'est également) mais tout fonctionne de mon côté (en local et en ligne). T'as utilisé la version `build` ou `Node.JS` ?

1. et 3. Je pense que le problème est au niveau de ta structure (car ton site ne lit pas les favicons). Si t'as repris le build, il faut créer un dossier `trpg-pannel` qui sera ton dossier source.
Exemple de mon côté serveur: 
![image](https://user-images.githubusercontent.com/61412526/146684565-e32076f5-2fd5-4f6a-97d4-da67bcc9f555.png)

2. Il faut mettre `[ ]` dans ton .json

**Comment by KyneSilverhide** [comment]
Salut, merci pour la réponse très rapide :)

J'ai utilisé la version node.js, et j'ai copié le "out" sur mon site. J'avais en effet laissé les favicon, mais je les ai ajouté
![2021-12-19 18_52_08-](https://user-images.githubusercontent.com/935348/146685349-13b062eb-ebb1-48f2-b37c-9743f96fc1a7.png)

J'ai voulu tester l'option static build, j'ai remplacé les occurrences de locahost, mais j'ai le même comportement. Sauf que je sais désormais cliquer sur la map et je vois le marqueur, je peux encoder une description, etc. Mais ca n'enregistre pas. Peut-être que c'est mon serveur privé qui bloque quelquechose.

**Comment by MacNaab** [comment]
D'accord c'est plus simple alors! Et ça donne quoi quand tu le lances en localhost ?

Assure toi que:
- `AppConfig.ts`:
```JS
const  URL = "https://witcher.kyne.ovh/api/";
```
- `next.config.js`:
```JS
basePath: '',
```
avant d'utiliser `npm run build-prod`. Qu'est ce que tu veux dire par static build ? Théoriquement ça ne devrait pas, tu peux toujours aller vérifier dans les fichiers `.json` s'ils ont bien été modifié ou non.

**Comment by KyneSilverhide** [comment]
Je n'ai pas testé en localhost, je n'ai pas de serveur PHP de dev et mon serveur OVH n'accepte pas (pour l'instant) le CORS, donc localhost ne pouvait pas contacter /api. Je verrai si je sais changer ca.

**Comment by MacNaab** [comment]
Oui normal. Si t'utilises visual studio code tu peux créer un serveur php local. J'utilise WampServer (car il était installé sur mon pc depuis quelques temps).
C'est vrai que si je devais refaire ce projet, je le coderai en Node.js et non php.

Si tu peux tester en local ce serait bien. Je pense que l'option VSC est la plus simple.

**Comment by KyneSilverhide** [comment]
Je suis sur Unix, et je n'ai pas WampServer.J'ai voulu passer par PHP CLI,
mais ca ne gère pas le CORS non plus :(

Blocage d’une requête multiorigine (Cross-Origin Request) : la politique «
Same Origin » ne permet pas de consulter la ressource distante située sur
http://127.0.0.1:8000/api/user/data.json. Raison : l’en-tête CORS «
Access-Control-Allow-Origin » est manquant.

J'ai essayé avec XAMPP mais j'ai aussi une erreur CORS. Malgré toutes les
configs que j'ai tenté dans Apache2...

Mais en tout cas merci pour les réponses ! Mais je me demande si je ne vais
pas essayer de développer moi même un petit quelquechose pour mon groupe.

**Comment by MacNaab** [comment]
Ah oui je crois que j'avais le même problème au début sous WAMP.
Est ce que t'as bien
```PHP
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET,POST,OPTIONS,PUT,DELETE*');
header('Access-Control-Allow-Headers: X-Requested-With*');
header('Content-Type: application/json;charset=UTF-8');
```
dans tes fichiers PHP ?

Normalement tu peux activer le CORS par PHP CLI.
Tu peux également essayer de faire un script php basic pour voir si ça fonctionne bien sur OVH.
*Je pense à quelque chose du genre*
```PHP
<?php 
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET,POST,OPTIONS,PUT,DELETE*');
header('Access-Control-Allow-Headers: X-Requested-With*');
header('Content-Type: application/json;charset=UTF-8');

$input = json_decode(file_get_contents('php://input'),true);
echo json_encode($input);
?>
```
*Et tu lances une requête toute simple vers ce fichier.*

---
Normalement j'ai mis la liste des npm si tu veux le refaire de ton côté. En local j'ai rajouté un bestiaire interactif (*en développement*).

---
Edit: je te dirais de regarder https://stackoverflow.com/questions/29617346/is-it-possible-to-enable-cors-in-the-php-cli-server *(mais je n'ai pas testé)*:
- Je commencerais par
``` PHP
php -S 127.0.0.1:8888 -t public
```
- sinon test son php routings script.

**Comment by KyneSilverhide** [comment]
Oui j'ai fais ca. Je n'y connais pas grand chose en PHP., mais j'ai testé via .htaccess, via la config apache2, etc... et j'ai rechargé à chaque fois mais ca ne voulait pas. Mais bon, en trichant un peu je peux modifier les fichiers JSON pour voir ce que l'application affiche, et je m'en inspirerai peut-être pour faire la mienne :)

On peut clôturer le bug, pour moi c'est en effet lié à l'environnement.

PS : j'ai tout de même dû mettre à jour react-rounder
` "react-rounder": "^1.1.1",`

Sinon ca ne buildait pas , une incompatibilité entre le type ReactNode et Element visiblement.

**Comment by MacNaab** [comment]
ça marche ! C'est quand même bizarre car certaines requêtes PHP fonctionne (je pense notamment au système de loggin).
Tu n'as toujours pas modifié `api/timeline/data.json`.

PS: J'ai fais un test de tes erreurs sur mon serveur live *(j'avais uniquement testé en local)*:
- #1, j'ai le même problème que toi (et pas en local). Je vais essayer d'investiguer un peu plus.. 
- #3, ça fonctionne très bien de mon côté, par contre c'est un "bug d'affichage": il suffit de recharger la page. (*UTILISATEUR* est bien mis à jour et la version mouseover de *MOT DE PASSE* également).

PPS: si tu veux faire ça de ton côte je te conseille de le faire en node.js à la place de PHP (vu que de toute manière t'es bloqué en PHP).

**Comment by MacNaab** [comment]
Je viens de mettre à jour. Le problème devrait être résolu.
